<?xml version="1.0"?>
<package format="3">
  <name>hector_imu_tools</name>
  <version>0.1.0</version>
  <description>IMU utilities for converting pose/orientation to IMU messages.</description>

  <maintainer email="you@example.com">Michael</maintainer>
  <license>BSD</license>

  <!-- Build system -->
  <buildtool_depend>ament_cmake</buildtool_depend>

  <!-- Dependencies -->
  <depend>rclcpp</depend>
  <depend>sensor_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>tf2</depend>
  <depend>tf2_ros</depend>
	<depend>std_srvs</depend>

  <!-- Launch files -->
  <exec_depend>ros2launch</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
