<?xml version="1.0"?>
<package format="3">
  <name>hector_imu_attitude_to_tf</name>
  <version>0.1.0</version>
  <description>Publishes IMU attitude as TF transforms.</description>

  <maintainer email="you@example.com">Michael</maintainer>
  <license>BSD</license>

  <!-- Build system -->
  <buildtool_depend>ament_cmake</buildtool_depend>

  <!-- Dependencies -->
  <depend>rclcpp</depend>
  <depend>sensor_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>tf2</depend>
  <depend>tf2_ros</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
